/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2021-12-21 02:34:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- header include -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/mainPage.css\">\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("    <section id=\"carousel\">\r\n");
      out.write("        <!-- Bootstrap Carousel-->\r\n");
      out.write("        <div id=\"carouselExampleDark\" class=\"carousel carousel-dark slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("              <div class=\"carousel-item active\" data-bs-interval=\"5000\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku2.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"carousel-item\" data-bs-interval=\"5000\" onclick=\"location.href='https://www.naver.com/'\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku3.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"carousel-item\" data-bs-interval=\"5000\" onclick=\"location.href='https://www.youtube.com/'\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku4.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleDark\" data-bs-slide=\"prev\">\r\n");
      out.write("              <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("              <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleDark\" data-bs-slide=\"next\">\r\n");
      out.write("              <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("              <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"middle-banner\">\r\n");
      out.write("        <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/mo.jpg\" alt=\"\"></div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"item-box\">\r\n");
      out.write("        <div><h3>새로운 상품 추천</h3></div>\r\n");
      out.write("        <div class=\"item\" id=\"it-1\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-2\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-3\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-4\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-5\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-6\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-7\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-8\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-9\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-10\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-11\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-12\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-13\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-14\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-15\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-16\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"img/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-17\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-18\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-19\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\" id=\"it-20\" onclick=\"location.href='https://m.bunjang.co.kr/'\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/ku.jpg\">\r\n");
      out.write("            <div class=\"item-title\">특히나 더 놀란 고양이</div>\r\n");
      out.write("            <div class=\"item-content\" style=\"font-weight: bold;\">\r\n");
      out.write("                <span style=\"float: left;\">12,000원</span>\r\n");
      out.write("                <span style=\"float: right;\">1일 전</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"page-button\">\r\n");
      out.write("            <div class=\"move-button\"><p>&#8249;</p></div>\r\n");
      out.write("            <div>1</div>\r\n");
      out.write("            <div>2</div>\r\n");
      out.write("            <div>3</div>\r\n");
      out.write("            <div>4</div>\r\n");
      out.write("            <div class=\"move-button\"><p>&#8250;</p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sideBar.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- footer include -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
